version: "1"

services:
  discord-app-server:
    network_mode: "host"
    ipc: host
    ports:
      - '3000:3000'
    image: "ddiff/discord:latest"
    build:
      context: ./apps/discord
      dockerfile: Dockerfile
    environment:
      APP_ID: ${APP_ID}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
  
  ngrok:
    image: wernight/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    command: ["ngrok", "http", "--domain=lucky-verbally-koala.ngrok-free.app", "discord-app-server:3000"]