version: '2.24.3'

services:
  flask-app:
    build: ./apps/diffusion
    ports:
      - '8000:8000'

  discord-app-server:
    build: ./apps/discord
    ports:
      - '3000:3000'
    environment:
      - APP_ID=${APP_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PUBLIC_KEY=${PUBLIC_KEY}
  
  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    command: ["ngrok", "http", "--domain=lucky-verbally-koala.ngrok-free.app", "discord-app-server:3000"]