name: ddiff
services:
  diffusion:
    build: ./apps/diffusion
    ports:
      - '8000:8000'

  discord-app-server:
    build: ./apps/discord
    container_name: discord-app-server
    ports:
      - '3000:3000'
    environment:
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - TESTING_GUILD=${TESTING_GUILD}
    networks:
      - mynet
  
  # ngrok:
  #   container_name: ngrok
  #   image: wernight/ngrok
  #   environment:
  #     - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
  #     - NGROK_PORT=discord-app-server:3000
  #   ports:
  #     - "0.0.0.0:4040:4040"
  #   command: ["ngrok", "http", "--domain=infinite-ghastly-terrier.ngrok-free.app", "discord-app-server:3000"]
  #   networks:
  #     - mynet

networks:
  mynet:
    driver: bridge