services:
  discord-app:
    image: "ddiff/discord:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      NODE_ENV: ${NODE_ENV:-production} # default NODE_ENV=production 

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      NGROK_DOMAIN: ${NGROK_DOMAIN}
    command: ["ngrok", "http", "--domain=${NGROK_DOMAIN}", "discord-app:3000"]
    profiles:
      - dev
