# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /

# Copy the current directory contents into the container at /app
COPY . /

# Install git
RUN apt-get update && apt-get install -y git

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install BentoML
RUN pip install bentoml

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define the command to run the BentoML service
# CMD ["bentoml", "serve", "service:SDXLTurbo"]
